output: String_HW.o String.o
	g++ -std=c++17 String_HW.o String.o

String_HW.o: String_HW.cpp String.h
	g++ -c -std=c++17 String_HW.cpp

String.o: String.cpp String.h
	g++ -c -std=c++17 String.cpp