output: String_test.o String.o
	g++ -std=c++17 String_test.o String.o

String_HW.o: String_test.cpp String.h
	g++ -c -std=c++17 String_HW.cpp

String.o: String.cpp String.h
	g++ -c -std=c++17 String.cpp